config/routes.rb
require 'sidekiq/web'

CodeTriage::Application.routes.draw do

  ENV.each do |var, _|
    next unless var.start_with?("ACME_TOKEN_")
    number = var.sub(/ACME_TOKEN_/, '')
    get ".well-known/acme-challenge/#{ ENV["ACME_TOKEN_#{number}"] }" => proc { [200, {}, [ ENV["ACME_KEY_#{number}"] ] ] }
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources   :doc_methods

  devise_for :users, skip: [:registration],
    :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # devise_scope(:user) do
  #   get 'sign_in',  to: 'users/omniauth_callbacks#passthru', as: :new_user_session
  #   get 'sign_out', to: 'users/omniauth_callbacks#passthru', as: :destroy_user_session
  # end

  as :user do
    get   'users/edit' => 'users#edit',   as: :edit_user_registration
    patch 'users'      => 'users#update', as: :user_registration
  end

  root to: "pages#index"

  namespace :users do
    resources :after_signup
  end

  resources   :users, except: [:new, :create, :index]
  get         "/users/unsubscribe/:account_delete_token" => "users#token_delete", as: :token_delete_user
  delete      "/users/unsubscribe/:account_delete_token" => "users#token_destroy"

  resources   :issue_assignments

  get "/issue_assignments/:id/users/:user_id/click",  to: "issue_assignments#click_issue_redirect", as: :issue_click
  get "/doc_methods/:id/users/:user_id/click",        to: "doc_methods#click_method_redirect",      as: :doc_method_click
  get "/doc_methods/:id/users/:user_id/source_click", to: "doc_methods#click_source_redirect",      as: :doc_source_click

  resources   :repo_subscriptions

  if Rails.env.development?
    mount UserMailer::Preview => 'mail_view'
  end

  # format: false gives us rails 3.0 style routes so angular/angular.js is interpreted as
  # user_name: "angular", name: "angular.js" instead of using the "js" as a format
  scope format: false do
    resources :repos, only: %w[index new create]

    scope '*full_name' do
      constraints full_name: /[-_a-zA-Z0-9]+\/[-_\.a-zA-Z0-9]+/ do
        get   '/badges/:badge_type(.:format)', to: 'badges#show',       as: 'badge'

        get   '/',              to: 'repos#show',        as: 'repo'
        patch '/',              to: 'repos#update',      as:  nil
        get   '/edit',          to: 'repos#edit',        as: 'edit_repo'
        get   '/subscribers',   to: 'subscribers#show',  as: 'repo_subscribers'
      end
    end
  end
end

app/models/github_fetcher/repo.rb
module GithubFetcher
  class Repo < Resource
    def initialize(options)
      @api_path = File.join(
        'repos',
        options.delete(:user_name),
        options.delete(:name),
      )
      super
    end

    def default_branch
      as_json['default_branch']
    end

    # TODO - does this really belong here? Seems like it (and Repo#populate_docs!)
    #   should move into the PopulateDocs job
    def clone
      `cd #{dir} && git clone #{clone_url} 2>&1`
      return dir
    end

    private

    # TODO - moves w/ clone
    def dir
      @dir ||= Dir.mktmpdir
    end

    # TODO - moves w/ clone
    def clone_url
      as_json["clone_url"]
    end

    # TODO - this appears to be uncalled... remove? or do we need it and should use it?
    def cleanup
      FileUtils.remove_entry(dir)
    end
  end
end

app/models/github_fetcher/repos.rb
module GithubFetcher
  class Repos < Resource
    KINDS = [
      OWNED = 'repos',
      STARRED = 'starred',
      SUBSCRIBED = 'subscriptions'
    ]

    def initialize(options)
      unless options[:kind].in? KINDS
        raise TypeError.new("kind must be one of #{KINDS.join(', ')} (#{options[:kind]} invalid)")
      end

      options[:type] = 'owner' if options[:kind] == OWNED

      @api_path = File.join(
        'user',
        options.delete(:kind),
      )
      super
    end
  end
end

app/models/repo.rb
require 'docs_doctor/parsers/ruby/yard'

class Repo < ActiveRecord::Base
  # Now done at the DB level # validates :name, uniqueness: {scope: :user_name, case_sensitive: false }
  validates :name, :user_name, presence: true
  validate :github_url_exists, on: :create

  has_many :issues
  has_many :repo_subscriptions
  has_many :users, through: :repo_subscriptions
  has_many :subscribers, through: :repo_subscriptions, source: :user
  has_many :doc_classes, dependent: :destroy
  has_many :doc_methods, dependent: :destroy
  delegate :open_issues, to: :issues

  before_validation :downcase_name, :strip_whitespaces
  before_save :set_full_name
  after_create :background_populate_issues!, :update_repo_info!, :background_populate_docs!

  CLASS_FOR_DOC_LANGUAGE = { "ruby" => DocsDoctor::Parsers::Ruby::Yard }

  def class_for_doc_language
    language && CLASS_FOR_DOC_LANGUAGE[language.downcase]
  end

  def can_doctor_docs?
    class_for_doc_language.present?
  end

  def fetcher
    @fetcher ||= GithubFetcher::Repo.new(user_name: user_name, name: name)
  end

  def fetcher_json
    fetcher.as_json
  end

  def issues_fetcher
    @issues_fetcher ||= GithubFetcher::Issues.new(
      user_name: user_name,
      name: name
    )
  end

  def commit_sha_fetcher
    @commit_sha_fetcher ||= GithubFetcher::CommitSha.new(
      user_name: user_name,
      name: name,
      default_branch: fetcher.default_branch
    )
  end

  def populate_docs!
    return unless can_doctor_docs?
    return unless commit_sha_fetcher.commit_sha

    self.update!(commit_sha: commit_sha_fetcher.commit_sha)
    parser = class_for_doc_language.new(fetcher.clone)
    parser.process
    parser.store(self)
  end

  def background_populate_issues!
    PopulateIssuesJob.perform_later(self)
  end

  def background_populate_docs!
    PopulateDocsJob.perform_later(self)
  end

  def methods_missing_docs
    doc_methods.where(doc_methods: {doc_comments_count: 0})
  end

  def methods_with_docs
    doc_methods.where("doc_comments_count > 0")
  end

  def classes_missing_docs
    doc_classes.where(doc_classes: {doc_comments_count: 0})
  end

  def color
    case weight
    when "low"
      "5bb878".freeze
    when "medium"
      "eba117".freeze
    when "high"
      "e25443".freeze
    else
      "lightgrey".freeze
    end
  end

  def weight
    case issues_count
    when 0..199
      "low".freeze
    when 200..799
      "medium".freeze
    when 800..Float::INFINITY
      "high".freeze
    else
      "".freeze
    end
  end

  def subscriber_count
    users.count
  end

  # pulls out number of issues divided by number of subscribers
  def self.order_by_need
     joins(:repo_subscriptions).order("issues_count::float/COUNT(repo_subscriptions.repo_id) DESC").group("repos.id")
  end

  # these repos have no subscribers and have no buisness being in our database
  def self.inactive
    joins("LEFT OUTER JOIN repo_subscriptions on repos.id = repo_subscriptions.repo_id").where("repo_subscriptions.repo_id is null")
  end

  def self.not_in(*ids)
    where("repos.id not in (?)", ids)
  end

  def self.rand
    order("random()")
  end

  def self.all_languages
    self.select("language").group("language").order("language ASC").map(&:language).reject(&:blank?)
  end

  def self.repos_needing_help_for_user(user)
    if user && user.has_favorite_languages?
      where(language: user.favorite_languages)
    else
      self
    end.with_some_issues.order_by_issue_count
  end

  def force_issues_count_sync!
     self.update_attributes(issues_count: self.issues.where(state: "open").count)
  end

  def to_param
    path
  end

  def self.order_by_issue_count
    self.order("issues_count DESC")
  end

  def self.search_by(repo_name, user_name)
    where(name: repo_name.downcase.strip, user_name: user_name.downcase.strip)
  end

  def self.with_some_issues
    self.where("issues_count > 0")
  end

  def github_url
    File.join('https://github.com', path)
  end

  def path
    "#{user_name}/#{name}"
  end

  def self.exists_with_name?(name)
    user_name, repo_name = name.downcase.split(?/)
    Repo.exists?(user_name: user_name, name: repo_name)
  end

  def self.order_by_subscribers
    joins("LEFT OUTER JOIN repo_subscriptions
           ON repo_subscriptions.repo_id = repos.id
           LEFT OUTER JOIN users ON users.id = repo_subscriptions.user_id").
      group("repos.id").
      order("count(users.id) DESC")
  end

  def update_from_github
    json = fetcher.as_json
    self.update(
      language: json.fetch('language', language),
      description: json.fetch('description', description),
      stars_count: json.fetch('stargazers_count', stars_count)
    )
  end

  def repo_path
    File.join 'repos', path
  end

  def self.find_by_full_name(full_name)
    Repo.find_by!(full_name: full_name)
  end

  private

  def update_repo_info!
    UpdateRepoInfoJob.perform_later(self)
  end

  def downcase_name
    self.name.downcase!
    self.user_name.downcase!
  end

  def set_full_name
    self.full_name = "#{user_name}/#{name}"
  end

  def strip_whitespaces
    self.name.strip!
    self.user_name.strip!
  end

  def github_url_exists
    if issues_fetcher.error?
      errors.add(
        :expiration_date,
        "cannot reach api.github.com/#{issues_fetcher.send(:api_path)} perhaps github is down, or you mistyped something?"
      )
    end
  end
end

app/controllers/repos_controller.rb
require File.expand_path("../../../lib/sorted_repo_collection", __FILE__)

class ReposController < RepoBasedController

  before_action :authenticate_user!, only: [:new, :create, :edit, :update]
  before_action :default_format

  def new
    @repo = Repo.new(user_name: params[:user_name], name: name_from_params(params))
    @repo_sub = RepoSubscription.new
    if user_signed_in?
      @own_repos     = cached_repos 'repos', current_user.own_repos_json
      @starred_repos = cached_repos 'starred', current_user.starred_repos_json
      @watched_repos = cached_repos 'subscriptions', current_user.subscribed_repos_json
    end
  end

  def show
    @repo        = find_repo(params)
    @issues      = @repo.open_issues.order("created_at DESC").page(params[:page]).per_page(params[:per_page]||20)
    @docs        = @repo.doc_methods.order("created_at DESC").page(params[:page]).per_page(params[:per_page]||20)

    @repo_sub    = current_user.repo_subscriptions_for(@repo.id).first if current_user
    @subscribers = @repo.subscribers.public_profile.limit(27)
  end

  def create
    parse_params_for_repo_info
    @repo   = Repo.search_by(params[:repo][:name], params[:repo][:user_name]).first unless params_blank?
    @repo ||= Repo.new(repo_params)
    if @repo.save
      @repo_sub = current_user.repo_subscriptions.create(repo: @repo)
      flash[:notice] = "Added #{@repo.to_param} for triaging"
      SendSingleTriageEmailJob.perform_later(@repo_sub.id)
      redirect_to @repo
    else
      @own_repos = current_user.own_repos_json
      render :new
    end
  end

  def edit
    @repo = find_repo(params)
    redirect_to root_path, notice: "You cannot edit this repo" unless current_user.able_to_edit_repo?(@repo)
  end

  def update
    @repo = find_repo(params)
    if @repo.update_attributes(repo_params)
      redirect_to @repo, notice: "Repo updated"
    else
      render :edit
    end
  end

  private
    def default_format
      request.format = "html"
    end

    def repo_params
      params.require(:repo).permit(
        :notes,
        :name,
        :user_name,
        :issues_count,
        :stars_count,
        :language,
        :description,
        :full_name
        )
    end

    def parse_params_for_repo_info
      if params[:url]
        params[:url].match(/^https:\/\/github\.com\/([^\/]*)\/([^\/]*)\/?$/)
        params[:repo] ||= {}
        params[:repo][:user_name] = $1.to_s
        params[:repo][:name] = $2.to_s
      end
    end

    def params_blank?
      repo_params.blank?
    end

    def cached_repos(kind, repos_json)
      Rails.cache.fetch("user/#{kind}/#{current_user.id}", expires_in: 30.minutes) do
        SortedRepoCollection.new(repos_json)
      end
    end
end

app/helpers/repos_helper.rb
module ReposHelper
  def link_to_or_log_in(options = {})
    path = user_signed_in? ? options[:path] : user_github_omniauth_authorize_path(origin: request.fullpath)
    button_to options[:text], path, class: "button #{options[:html_class]}"
  end
end

app/views/repos/_badge.html.slim
- code_triagers_badge_url = File.join(repo_url(@repo), "badges/users.svg")

ul.accordion-tabs
  li.tab-header-and-content
    a.is-active.tab-link href="javascript:void(0)" Image URL
    .tab-content.is-open
      textarea
        = code_triagers_badge_url
  li.tab-header-and-content
    a.tab-link href="javascript:void(0)" Markdown
    .tab-content
      textarea
        | [![Code Triagers Badge](#{code_triagers_badge_url})](#{repo_url(@repo)})
  li.tab-header-and-content
    a.tab-link href="javascript:void(0)" Textile
    .tab-content
      textarea
        | !#{code_triagers_badge_url}!:#{repo_url(@repo)}
  li.tab-header-and-content
    a.tab-link href="javascript:void(0)" Rdoc
    .tab-content
      textarea
        | {<img src='#{code_triagers_badge_url}' alt='Code Triagers Badge' />}[#{repo_url(@repo)}]

app/views/repos/_repo.html.slim
= cache repo do
  li class="repo-item #{ repo.weight }" data-language="#{ repo.language if repo.language }"
    = link_to repo
      header.repo-item-header
        h4.repo-item-title = repo.name
        span.repo-item-issues
          = warning_svg
          = repo.issues_count
          |  Issues

      p.repo-item-description = repo.description

      - if repo.full_name.present?
        span.repo-item-full-name
          | (#{repo.full_name})

app/views/repos/edit.html.slim
h2 Editing repo #{@repo.full_name}

= form_for @repo do |f|

  p
    | As a repo owner you are able to add some text to your repos page to encourage users to subscribe to your project and help out.
      You may also want to add additional information on the best ways to help out and any common things that people might want to know in advance.
  p Markdown is supported here

  p= f.text_area :notes, class: 'span6', rows: 5

  div
    => f.submit "Update repo", class: 'btn btn-primary'
    = link_to "Cancel", repo_path(@repo), class: 'btn'

app/views/repos/new.html.slim
- @repo.errors.full_messages.each do |msg|
  li= msg

.subpage-content-wrapper
  .subpage-content-header
    h1.subpage-primary-title Add a new repo to CodeTriage

  - if user_signed_in?
    section.content-section
      h2.content-section-title Your repos
      p Only repos that have GitHub issues enabled are shown

      ul.nav-tabs#repo-tabs data-tabs="tabs"
        li.nav-tabs-item.active
          a href="#own" data-toggle="tab"
            | Your repos
        li.nav-tabs-item
          a href="#starred" data-toggle="tab"
            | Starred repos
        li.nav-tabs-item
          a href="#watched" data-toggle="tab"
            | Watched repos

      .tab-content
        .tab-pane.active#own
          = render 'shared/add_repos_list', repos: @own_repos

        .tab-pane#starred
          = render 'shared/add_repos_list', repos: @starred_repos

        .tab-pane#watched
          = render 'shared/add_repos_list', repos: @watched_repos

  section.content-section
    h2.content-section-title Add another repo by pasting the full repo URL

    = form_tag repos_path, { class: "new_repo", id: "new_repo_from_url" } do
      => text_field_tag :url, nil, placeholder: 'full url e.g. "https://github.com/schneems/sextant', class: 'url_field'
      = submit_tag nil, value: "Add Repo", class: 'button full-width-action', id: 'createRepo'

app/views/repos/show.html.slim
div class="subpage-content-wrapper #{ @repo.weight }"
  header.subpage-content-header
    = link_to @repo.github_url
      h1.subpage-primary-title= @repo.name
      p.subpage-secondary-title= @repo.github_url
      h2.repo-language= @repo.language
      p.repo-description= @repo.description

  .repo-body
    section.help-triage.content-section
      - if @repo_sub.blank?
        h2.content-section-title Triage Issues!
        p.repo-instructions
          | When you volunteer to triage issues, you'll receive an email each day with a link to an open issue that needs help in this project.
            You'll also receive instructions on how to triage issues.

        = link_to_or_log_in(text: "Triage Issues", path: repo_subscriptions_path(repo_subscription: { repo_id: @repo.id, email_limit: 3}), html_class: "repo-action")

      - else
        h2.content-section-title Currently receiving #{@repo_sub.email_limit} issues per day.
        .repo-instructions
          = form_for(@repo_sub, html: { class: 'email-amount'} ) do |f|
            label Triage more issues! (Or less)
            => f.select :email_limit, (0..20)
            = f.submit "Save", class: 'save-amount'
        - if (@repo_sub.email_limit > 0)
          = link_to issue_assignments_path(id: @repo_sub.id), class: 'button repo-action', method: :post do
            | Send me a new issue!

    section.help-triage.content-section
      - if @repo_sub.blank? || (@repo_sub.write.blank? && @repo_sub.read.blank?)
        h2.content-section-title Triage Docs!
        p.repo-instructions
          | Receive a documented method or class from your favorite GitHub repos in your inbox every day. If you're really pro, receive undocumented methods or classes and supercharge your commit history.
        - if @repo.can_doctor_docs?
          = link_to_or_log_in(text: "Triage Docs", path: repo_subscriptions_path(id: @repo_sub.try(:id), repo_subscription: { repo_id: @repo.id, read: true, write: true,  read_limit: 3, write_limit: 3, email_limit: @repo_sub.try(:email_limit) || 0 }), html_class: "repo-action")
        - else
          = link_to "#{@repo.language} not yet supported", '#', class: "button inactive repo-action"

      - else
          h2.content-section-title Currently receiving #{@repo_sub.write_limit + @repo_sub.read_limit} docs per day.
          .repo-instructions
            = form_for(@repo_sub, html: {class: 'email-amount'}) do |f|
              label Triage more docs! (Or less)
              = f.label "Read Docs"
              = f.select :read_limit, (0..20)
              = f.submit "Save", class: 'save-amount'
              = f.label "Write Docs"
              => f.select :write_limit, (0..20)
              = f.submit "Save", class: 'save-amount'

      - if user_signed_in? && current_user.able_to_edit_repo?(@repo)
        section.content-section
          = link_to "Edit this repo", edit_repo_path(@repo), class: 'button full-width-action'

    section.avatars.content-section
      h2.content-section-title
        = pluralize(@repo.subscribers.size, 'Subscriber'.pluralize())
      ul.avatars-list
        = render 'subscribers/avatars', subscribers: @subscribers, show_names: false

      - if (difference = @repo.subscribers.count - @subscribers.count) && difference > 0
        = link_to 'View all Subscribers' , repo_subscribers_path(full_name: @repo.full_name)

    section.content-section
      h2.content-section-title
        | Add a CodeTriage badge to #{@repo.name}
        img.repo-badge src="#{ File.join(repo_path(@repo), "badges/users.svg?count=#{@repo.subscribers.size}") }" /
      = render partial: "badge"




    section.open-issues.content-section
      h2.content-section-title= "Help out"
      ul.accordion-tabs
        li.tab-header-and-content
          a.is-active.tab-link href="javascript:void(0)" Issues
          .tab-content.is-open
            ul.slats-list
              - @issues.each do |issue|
                li.slats-item
                  = warning_svg
                  = link_to issue.title, issue.html_url

            .pagination= will_paginate @issues, total_entries: @repo.issues_count, container: false
        li.tab-header-and-content
          a.tab-link href="javascript:void(0)" Docs
          .tab-content
            ul.slats-list
              - @docs.each do |doc|
                li.slats-item
                  = doc.missing_docs? ? warning_svg : "<span class='issue-icon'>🚀</span>".html_safe
                  = link_to doc.path, doc

            .pagination= will_paginate @docs, container: false

    - if @repo_sub
      = link_to repo_subscription_path(@repo_sub), class: 'button stop-triaging full-width-action', method: :delete, data: { confirm: 'Are you sure?' } do
          | Stop Triaging