config/routes.rb
require 'sidekiq/web'

CodeTriage::Application.routes.draw do

  ENV.each do |var, _|
    next unless var.start_with?("ACME_TOKEN_")
    number = var.sub(/ACME_TOKEN_/, '')
    get ".well-known/acme-challenge/#{ ENV["ACME_TOKEN_#{number}"] }" => proc { [200, {}, [ ENV["ACME_KEY_#{number}"] ] ] }
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources   :doc_methods

  devise_for :users, skip: [:registration],
    :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # devise_scope(:user) do
  #   get 'sign_in',  to: 'users/omniauth_callbacks#passthru', as: :new_user_session
  #   get 'sign_out', to: 'users/omniauth_callbacks#passthru', as: :destroy_user_session
  # end

  as :user do
    get   'users/edit' => 'users#edit',   as: :edit_user_registration
    patch 'users'      => 'users#update', as: :user_registration
  end

  root to: "pages#index"

  namespace :users do
    resources :after_signup
  end

  resources   :users, except: [:new, :create, :index]
  get         "/users/unsubscribe/:account_delete_token" => "users#token_delete", as: :token_delete_user
  delete      "/users/unsubscribe/:account_delete_token" => "users#token_destroy"

  resources   :issue_assignments

  get "/issue_assignments/:id/users/:user_id/click",  to: "issue_assignments#click_issue_redirect", as: :issue_click
  get "/doc_methods/:id/users/:user_id/click",        to: "doc_methods#click_method_redirect",      as: :doc_method_click
  get "/doc_methods/:id/users/:user_id/source_click", to: "doc_methods#click_source_redirect",      as: :doc_source_click

  resources   :repo_subscriptions

  if Rails.env.development?
    mount UserMailer::Preview => 'mail_view'
  end

  # format: false gives us rails 3.0 style routes so angular/angular.js is interpreted as
  # user_name: "angular", name: "angular.js" instead of using the "js" as a format
  scope format: false do
    resources :repos, only: %w[index new create]

    scope '*full_name' do
      constraints full_name: /[-_a-zA-Z0-9]+\/[-_\.a-zA-Z0-9]+/ do
        get   '/badges/:badge_type(.:format)', to: 'badges#show',       as: 'badge'

        get   '/',              to: 'repos#show',        as: 'repo'
        patch '/',              to: 'repos#update',      as:  nil
        get   '/edit',          to: 'repos#edit',        as: 'edit_repo'
        get   '/subscribers',   to: 'subscribers#show',  as: 'repo_subscribers'
      end
    end
  end
end

app/models/github_fetcher/user.rb
module GithubFetcher
  class User < Resource
    def initialize(options)
      @api_path = '/user'
      super
    end

    def valid?
      begin
        GitHubBub.valid_token?(@options[:token])
      rescue GitHubBub::RequestError
        false
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules (but not :registerable). Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable,
  # :omniauthable, and :registerable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :omniauthable

  validates_uniqueness_of :email,    allow_blank: true, if: :email_changed?
  validates_length_of     :password, within:  8..128, allow_blank: true
  validates :github, presence: true, uniqueness: true
  validates :email_frequency, inclusion: { in: EmailRateLimit::USER_STATES.map(&:to_s) + [nil] , message: "Not a valid frequency, pick from #{ EmailRateLimit::USER_STATES }" }

  # Setup accessible (or protected) attributes for your model

  has_many :repo_subscriptions, dependent: :destroy
  has_many :repo_assignments, through: :repo_subscriptions
  has_many :repos, through: :repo_subscriptions

  has_many :issue_assignments, through: :repo_subscriptions
  has_many :issues,            through: :issue_assignments

  scope :public_profile, -> { where.not(users: { private: true }) }

  alias_attribute :token, :github_access_token

  delegate :for, to: :repo_subscriptions, prefix: true
  before_save :set_default_last_clicked_at

  def subscribe_docs!
    subscriptions = self.repo_subscriptions.order('RANDOM()').load
    DocMailerMaker.new(self, subscriptions) {|sub| sub.ready_for_next? }.deliver_later
  end

  def set_default_last_clicked_at
    self.last_clicked_at ||= Time.now
  end

  def own_repos_json(per_page = 100)
    repos_fetcher(GithubFetcher::Repos::OWNED, token: token, per_page: per_page.to_s).as_json
  end

  def starred_repos_json
    repos_fetcher(GithubFetcher::Repos::STARRED, token: token).as_json
  end

  def subscribed_repos_json
    repos_fetcher(GithubFetcher::Repos::SUBSCRIBED, token: token).as_json
  end

  def fetcher
    @fetcher ||= GithubFetcher::User.new(token: token)
  end

  def repos_fetcher(kind, options = {})
    GithubFetcher::Repos.new({ token: token, kind: kind }.merge(options))
  end

  def auth_is_valid?
    fetcher.valid?
  end

  def self.random
    order("RANDOM()")
  end

  # users that are not subscribed to any repos
  def self.inactive
    joins("LEFT OUTER JOIN repo_subscriptions on users.id = repo_subscriptions.user_id").where("repo_subscriptions.user_id is null")
  end

  def default_avatar_url
    "http://gravatar.com/avatar/default"
  end

  def account_delete_token
    if self[:account_delete_token].blank?
      self.account_delete_token = SecureRandom.hex(64)
      update_attribute(:account_delete_token, account_delete_token) unless new_record?
    end

    self[:account_delete_token]
  end

  def enqueue_inactive_email
    background_inactive_email(self.id)
  end

  def able_to_edit_repo?(repo)
    repo.user_name == github.downcase
  end

  def public?
    !private
  end

  def not_yet_subscribed_to?(repo)
    !subscribed_to?(repo)
  end

  def subscribed_to?(repo)
    sub_from_repo(repo).present?
  end

  def sub_from_repo(repo)
    self.repo_subscriptions.find_by(repo_id: repo.id)
  end

  def github_json
    fetcher.json
  end

  def fetch_avatar_url
    github_json["avatar_url"]
  end

  def set_avatar_url!
    self.avatar_url = self.fetch_avatar_url || default_avatar_url
    self.save!
  end

  def github_url
    "https://github.com/#{github}"
  end

  def valid_email?
    ValidateEmail.valid?(email)
  end

  def days_since_last_clicked
    return 0 if last_clicked_at.blank?
    (
      (Time.now - last_clicked_at) / 1.day
    ).ceil # only want whole days
  end

  def days_since_last_email
    last_sent_at = repo_subscriptions.last.try(:last_sent_at)
    last_sent_at ||= self.created_at
    (
      (Time.now - last_sent_at) / 1.day
    ).ceil # only want whole days
  end

  def favorite_language?(language)
    favorite_languages.include? language if favorite_languages
  end

  def has_favorite_languages?
    favorite_languages && !favorite_languages.empty?
  end

  def issue_assignments_to_deliver(assign: true)
    issue_assigner.assign! if assign
    issue_assignments.where(delivered: false).limit(daily_issue_limit)
  end

  private

  def issue_assigner
    @issue_assigner ||= IssueAssigner.new(self, repo_subscriptions)
  end
end

app/controllers/users/after_signup_controller.rb
class Users::AfterSignupController < ApplicationController

  include Wicked::Wizard

  before_action :authenticate_user!

  steps :set_privacy

  def show
    @user = current_user
    render_wizard
  end

  def update
    @user = current_user
    @user.update_attributes(user_params)
    render_wizard @user
  end

  private

    def user_params
      params.require(:user).permit(
        :private,
        :email,
        :password,
        :password_confirmation,
        :remember_me,
        :zip,
        :phone_number,
        :twitter,
        :github,
        :github_access_token,
        :avatar_url,
        :name,
        :favorite_languages,
        :daily_issue_limit
        )
    end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def github
    @user = GitHubAuthenticator.authenticate(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      if @user.valid_email?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", kind: "GitHub"
      else
        flash[:notice] = I18n.t "devise.omniauth_callbacks.bad_email_success", kind: "GitHub"
      end

      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.github_data"] = request.env["omniauth.auth"].delete("extra")
      flash[:error]  = no_email_error if request.env["omniauth.auth"].info.email.blank?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.failure",
                       kind: "GitHub", reason: "Invalid credentials" if flash[:error].blank?
      redirect_to root_path
    end
  end

  private

  def no_email_error
    msg =  "You need a public email address on GitHub to sign up you can add"
    msg << " an email, sign up for triage, then remove it from GitHub:<hr />"
    msg << "<a href='https://github.com/settings/profile'>GitHub Profile</a>"
    msg.html_safe
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, only: [:edit, :update, :destroy]

  def show
    @user = User.find(params[:id])
    if @user.private?
      redirect_to root_path unless current_user && @user == current_user
    end
  end

  def edit
    @user = current_user
  end

  def update
    begin
      uparams = user_params
    rescue ActionController::ParameterMissing
      uparams = {favorite_languages: []}
    end

    @user = current_user
    if @user.update_attributes(uparams)
      redirect_to @user, flash: { success: 'User successfully updated' }
    end
  end

  def destroy
    @user = current_user
    @user.destroy
    redirect_to root_url, notice: "Successfully removed your user account"
  end

  def token_delete
    @user = User.find_by(account_delete_token: params[:account_delete_token])
    if @user.nil?
      redirect_to root_url, notice: "Account could not be found. You may have already deleted it, or your GitHub username may have changed."
    end
  end

  def token_destroy
    @user = User.find_by!(account_delete_token: params[:account_delete_token])
    @user.destroy
    redirect_to root_url, notice: "Successfully removed your user account"
  end

  private

    def user_params
      params.require(:user).permit(
        :private,
        :email,
        :password,
        :password_confirmation,
        :remember_me,
        :zip,
        :phone_number,
        :twitter,
        :github,
        :github_access_token,
        :avatar_url,
        :name,
        :daily_issue_limit,
        :email_frequency,
        :email_time_of_day,
        :skip_issues_with_pr,
        favorite_languages: []
        )
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def available_times_of_day
    (0...24).map { |hour| Time.utc(2000, 1, 1, hour, 00, 0) }
  end
end

app/views/users/_form.html.slim
.clearfix
  = f.label :email, t("activerecord.attributes.user.email", default: "Email"), class: "label label-info"
  .controls
    .input-prepend
      span.add-on
        i.icon-envelope
      = f.text_field :email, class: 'text_field'
  = f.label :email_frequency, t("activerecord.attributes.user.email_frequency", default: "Email Frequency"), class: "label label-info"
  .controls
    .input-preprend
      span.add-on
        i.icon-envelope
      = f.select :email_frequency, options_for_select( EmailRateLimit::USER_STATES.map {|value| [ value.humanize, value ] }, f.object.email_frequency), class: 'select'
      p When you're busy we try to send you less emails, if that's not good enough set your frequency here. For example if you set "twice a week" you won't receive more than 2 emails a week.

  = f.label :email_time_of_day, t("activerecord.attributes.user.email_time_of_day", default: "Email time of day"), class: "label label-info"
  .controls
    .input-preprend
      span.add-on
        i.icon-envelope
      = f.select :email_time_of_day,
          options_for_select(available_times_of_day.map { |time| [time.to_formatted_s(:time_only_with_zone), time.to_formatted_s(:iso8601)] }, f.object.email_time_of_day&.to_formatted_s(:iso8601)),
          class: 'select'

  = f.label :daily_issue_limit, t("activerecord.attributes.user.daily_issue_limit", default: "Max # of issues you want to receive per day"), class: "label label-info"
  .input
    = f.number_field :daily_issue_limit, class: 'number_field', min: 0
    p If you're getting too many issues, limit the maximum number you want to get in your inbox at one time. To disable submit an empty value.

  = f.check_box :skip_issues_with_pr, class: 'checkbox'
  => f.label :skip_issues_with_pr, t("activerecord.attributes.user.skip_issues_with_pr", default: "Skip Pull requests"), class: "label label-info"
  p By default we send you a combination of issues and pull request, check this box to only get Issues.

.form-actions
  => button_tag "Save", class: "button full-width-action"

app/views/users/edit.html.slim
.subpage-content-wrapper
  section.subpage-content-header
    h1.subpage-primary-title
      | Edit 
      = @user.github

  section.user-settings.content-section
    = form_for @user, url: user_path(@user), method: :patch, html: { class: "edit_user", id: "edit_user" } do |f|
      = render partial: "form", locals: {f: f}

app/views/users/show.html.slim
- if current_user.blank?
  section.user-logged-out
    h1= link_to 'Login to view yor account', user_github_omniauth_authorize_path

- if current_user && current_user == @user
  .subpage-content-wrapper
    section.subpage-content-header
      h1.subpage-primary-title= @user.github
      h2.subpage-secondary-title.user-email= @user.email

      .subpage-header-actions
        = link_to 'Delete Account'.html_safe, user_path(@user), method: "delete", confirm: "#{t("web-app-theme.confirm", default: "Are you sure?")}"
        = link_to 'Edit Account'.html_safe, edit_user_path(@user), class: 'header-primary-action'

    section.user-settings.content-section
      h2.content-section-title Settings

      ul.slats-list
        li.slats-item
          .slats-hgroup
            h3 Is your account shown to everyone:

          .slats-action
            p
              - if @user.public?
                | Public,
                = link_to "Go private", user_registration_path(user: {private: true}), method: :patch
              - else
                | Private,
                = link_to "Go public", user_registration_path(user: {private: false}), method: :patch
        li.slats-item
          .slats-hgroup
            h5.slats-title Email frequency:
          .slats-action
            p= @user.email_frequency.presence || 'not set'

        li.slats-item
          .slats-hgroup
            h5.slats-title Email time of day:
          .slats-action
            p= (@user.email_time_of_day && local_time(@user.email_time_of_day, '%H:%M %Z')) || 'not set'
            
        li.slats-item
          .slats-hgroup
            h5.slats-title Max number of issues you want to receive per day:
          .slats-action
            p= @user.daily_issue_limit.presence || 'not set'

        li.slats-item
          .slats-hgroup
            h5.slats-title Skip Issues with Pull Requests:
          .slats-action
            p= @user.skip_issues_with_pr

    section.user-favorite-langs.content-section
      h2.content-section-title Select your favorite languages:
      = form_for @user do |f|
        ul.all-languages-list
          - Repo.all_languages.each do |language|
            li.language-item
              = f.check_box :favorite_languages, { multiple: true }, language, nil
              = f.label language
        p= button_tag "Save Favorite Languages", class: "button full-width-action"

app/views/users/token_delete.html.slim
.alert.alert-error
  | Are you sure you want to delete your account and stop receiving triage emails at
  strong= @user.email
  | ?
= form_for @user, url: token_delete_user_path(@user.account_delete_token), method: :delete, html_options: { class: "form form-horizontal" } do |f|
  = f.submit "Yes, Delete My Account", class: "btn btn-danger"
  = link_to "No, Cancel", root_url, class: "btn"