config/routes.rb
require 'sidekiq/web'

CodeTriage::Application.routes.draw do

  ENV.each do |var, _|
    next unless var.start_with?("ACME_TOKEN_")
    number = var.sub(/ACME_TOKEN_/, '')
    get ".well-known/acme-challenge/#{ ENV["ACME_TOKEN_#{number}"] }" => proc { [200, {}, [ ENV["ACME_KEY_#{number}"] ] ] }
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources   :doc_methods

  devise_for :users, skip: [:registration],
    :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # devise_scope(:user) do
  #   get 'sign_in',  to: 'users/omniauth_callbacks#passthru', as: :new_user_session
  #   get 'sign_out', to: 'users/omniauth_callbacks#passthru', as: :destroy_user_session
  # end

  as :user do
    get   'users/edit' => 'users#edit',   as: :edit_user_registration
    patch 'users'      => 'users#update', as: :user_registration
  end

  root to: "pages#index"

  namespace :users do
    resources :after_signup
  end

  resources   :users, except: [:new, :create, :index]
  get         "/users/unsubscribe/:account_delete_token" => "users#token_delete", as: :token_delete_user
  delete      "/users/unsubscribe/:account_delete_token" => "users#token_destroy"

  resources   :issue_assignments

  get "/issue_assignments/:id/users/:user_id/click",  to: "issue_assignments#click_issue_redirect", as: :issue_click
  get "/doc_methods/:id/users/:user_id/click",        to: "doc_methods#click_method_redirect",      as: :doc_method_click
  get "/doc_methods/:id/users/:user_id/source_click", to: "doc_methods#click_source_redirect",      as: :doc_source_click

  resources   :repo_subscriptions

  if Rails.env.development?
    mount UserMailer::Preview => 'mail_view'
  end

  # format: false gives us rails 3.0 style routes so angular/angular.js is interpreted as
  # user_name: "angular", name: "angular.js" instead of using the "js" as a format
  scope format: false do
    resources :repos, only: %w[index new create]

    scope '*full_name' do
      constraints full_name: /[-_a-zA-Z0-9]+\/[-_\.a-zA-Z0-9]+/ do
        get   '/badges/:badge_type(.:format)', to: 'badges#show',       as: 'badge'

        get   '/',              to: 'repos#show',        as: 'repo'
        patch '/',              to: 'repos#update',      as:  nil
        get   '/edit',          to: 'repos#edit',        as: 'edit_repo'
        get   '/subscribers',   to: 'subscribers#show',  as: 'repo_subscribers'
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_action do
    if current_user && current_user.admin?
      Rack::MiniProfiler.authorize_request
    end
  end

  before_action do
    if current_user
      Raven.user_context email: current_user.email, id: current_user.id, username: current_user.github
    end
  end

  def authenticate_user!
    redirect_to user_github_omniauth_authorize_path(origin: request.fullpath) unless user_signed_in?
  end

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) || root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  WARNING_SVG = %Q{
    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" viewBox="0 0 16 16" class="issue-icon">
      <path style="fill-rule:evenodd;clip-rule:evenodd;" d="M8,0C3.582,0,0,3.582,0,8s3.582,8,8,8s8-3.582,8-8S12.418,0,8,0z M8,14 c-3.309,0-6-2.692-6-6s2.691-6,6-6c3.307,0,6,2.692,6,6S11.307,14,8,14z"/>
      <path style="fill-rule:evenodd;clip-rule:evenodd;" d="M8.5,3h-1C7.224,3,7,3.224,7,3.5v6C7,9.776,7.224,10,7.5,10h1 C8.776,10,9,9.776,9,9.5v-6C9,3.224,8.776,3,8.5,3z"/>
      <path style="fill-rule:evenodd;clip-rule:evenodd;" d="M8.5,11h-1C7.224,11,7,11.224,7,11.5v1C7,12.776,7.224,13,7.5,13h1 C8.776,13,9,12.776,9,12.5v-1C9,11.224,8.776,11,8.5,11z"/>
    </svg>
  }.html_safe

  STAR_SVG = %Q{
    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" viewBox="0 0 16 16" class="star-icon">
      <polygon fill="white" stroke="white" stroke-width="2" points="8,3 12,13 3,7 13,7 4,13" />
    </svg>
  }.html_safe


  def flash_class(level)
    case level
    when :notice then 'info'
    when :error then 'error'
    when :alert then 'warning'
    end
  end

  def warning_svg
    WARNING_SVG
  end

  def star_svg
    STAR_SVG
  end

  # Render custom or default meta
  # tags inside the header
  def render_meta_tags
    content_for?(:meta_tags) ? content_for(:meta_tags) : render('default_meta_tags'.freeze)
  end
end

app/views/application/_default_meta_tags.html.slim
meta name="name" content="CodeTriage"
meta name="description" content="Help out your favorite open source projects and become a better developer while doing it"

app/views/application/_down.html.slim
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" viewBox="0 0 16 16" class="down-circle">
  <path style="fill-rule:evenodd;clip-rule:evenodd;" d="M5.327,6h5.347c0.296,0,0.411,0.202,0.26,0.451l-2.658,4.362 c-0.151,0.249-0.398,0.249-0.55,0L5.066,6.451C4.915,6.202,5.031,6,5.327,6z"/>
  <path style="fill-rule:evenodd;clip-rule:evenodd;" d="M8,0C3.582,0,0,3.582,0,8s3.582,8,8,8s8-3.582,8-8S12.418,0,8,0z M8,14 c-3.309,0-6-2.691-6-6s2.691-6,6-6s6,2.691,6,6S11.309,14,8,14z"/>
</svg>

app/views/application/_flashes.html.slim
- [:notice, :error, :alert, :success].each do |level|
  - unless flash[level].blank?
    div class="alert flash-#{level}"
      = content_tag :p, flash[level]

app/views/application/_footer.html.slim
footer.application-footer
  hr.section-break
  = link_to "Submit a Repo", new_repo_path, class: 'button footer-action'

  .github-numbers
    <iframe src="https://ghbtns.com/github-btn.html?user=codetriage&repo=codetriage&type=watch&count=true&v=2" frameborder="0" scrolling="0" width="100px" height="20px"></iframe>
    <iframe src="https://ghbtns.com/github-btn.html?user=codetriage&repo=codetriage&type=star&count=true" frameborder="0" scrolling="0" width="100px" height="20px"></iframe>
    <iframe src="https://ghbtns.com/github-btn.html?user=codetriage&repo=codetriage&type=fork&count=true" frameborder="0" scrolling="0" width="100px" height="20px"></iframe>

  p.credits
    a href="https://www.schneems.com" class="credits-link"
      = render 'schneems'
      | Created by Schneems

    a href="https://thoughtbot.com" class="credits-link"
      = render 'thoughtbot'
      | Designed by thoughtbot

    a href="https://www.heroku.com" class="credits-link"
      = render 'heroku'
      | Powered by Heroku

  p
    | &copy; CodeTriage
    = Time.now.year

app/views/application/_head.html.slim
head
  meta charset="utf-8"
  title CodeTriage

  meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"
  meta name="viewport" content="width=device-width, initial-scale=1.0"
  = csrf_meta_tags

  = stylesheet_link_tag "application", media: "all"

  link rel="shortcut icon" href="/favicon.ico" type="image/x-icon"
  link rel="icon" href="/favicon.ico" type="image/x-icon"

  <script src="//use.typekit.net/vyg4pus.js"></script>
  <script>try{Typekit.load({ async: true  });}catch(e){}</script>

  = render_meta_tags

  = javascript_include_tag "application", async: true

  - if Rails.env.production?
    /! google analytics
    javascript:
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-102491943-1', 'auto');
      ga('send', 'pageview');

app/views/application/_logo.html.slim
<svg width="200px" height="56px" viewBox="0 0 200 56" xmlns="http://www.w3.org/2000/svg">
  <path d="M39.9017053,0.635733333 L28.9141182,0.635733333 C26.6645106,0.635733333 24.8356312,2.45475556 24.8356312,4.68906667 L24.8356312,20.7104 C24.8356312,22.9447111 26.6645106,24.7623111 28.9141182,24.7623111 L39.9017053,24.7623111 C42.1513128,24.7623111 43.9816233,22.9447111 43.9816233,20.7104 L43.9816233,4.68906667 C43.9816233,2.45475556 42.1513128,0.635733333 39.9017053,0.635733333" id="Fill-1" fill="#E05548"></path>
  <path d="M65.9253144,47.3230222 C64.8477352,48.4266667 62.5995587,50.2001778 58.2591899,50.2001778 C52.0083719,50.2001778 47.1141875,46.0999111 47.1141875,39.3073778 C47.1141875,32.4835556 52.069907,28.4145778 58.2591899,28.4145778 C62.6310418,28.4145778 65.0022884,30.2193778 65.556104,30.8010667 L64.0162963,34.9013333 C63.6156028,34.3808 61.3373743,32.6983111 58.5353822,32.6983111 C54.9334342,32.6983111 52.1629251,35.0848 52.1629251,39.2149333 C52.1629251,43.3450667 55.0565043,45.7031111 58.5353822,45.7031111 C61.1842522,45.7031111 63.0918392,44.6620444 64.2624366,43.4673778 L65.9253144,47.3230222" id="Fill-2" fill="#FFFFFF"></path>
  <path d="M74.9781245,50.1688889 C70.1755272,50.1688889 66.5420961,47.2007111 66.5420961,42.3367111 C66.5420961,37.4712889 70.1755272,34.4718222 74.9781245,34.4718222 C79.7807218,34.4718222 83.3841009,37.4712889 83.3841009,42.3367111 C83.3841009,47.2007111 79.7807218,50.1688889 74.9781245,50.1688889 L74.9781245,50.1688889 Z M74.9781245,38.3274667 C72.7914831,38.3274667 71.5307297,40.0113778 71.5307297,42.2442667 C71.5307297,44.4785778 72.7914831,46.1610667 74.9781245,46.1610667 C77.1332829,46.1610667 78.4269504,44.4785778 78.4269504,42.2442667 C78.4269504,40.0113778 77.1332829,38.3274667 74.9781245,38.3274667 L74.9781245,38.3274667 Z" id="Fill-3" fill="#FFFFFF"></path>
  <path d="M101.641412,49.8332444 L96.9618849,49.8332444 L96.991937,47.8449778 L96.9003499,47.8748444 C95.7612356,49.4051556 93.9452356,50.1688889 91.9131474,50.1688889 C87.5098125,50.1688889 84.7378723,46.7427556 84.7378723,42.3054222 C84.7378723,37.8695111 87.5098125,34.4718222 91.9131474,34.4718222 C94.6836564,34.4718222 96.2234641,35.8499556 96.7157447,36.5838222 L96.7157447,28.7189333 L101.641412,28.7189333 L101.641412,49.8332444 L101.641412,49.8332444 Z M93.3284539,38.3274667 C91.2047786,38.3274667 89.757989,39.9189333 89.757989,42.2442667 C89.757989,44.5710222 91.2047786,46.1610667 93.3284539,46.1610667 C95.4535603,46.1610667 96.8702979,44.5710222 96.8702979,42.2442667 C96.8702979,39.9189333 95.4535603,38.3274667 93.3284539,38.3274667 L93.3284539,38.3274667 Z" id="Fill-4" fill="#FFFFFF"></path>
  <path d="M118.945645,43.4673778 L108.13837,43.4673778 C108.354459,45.6419556 110.017336,46.6204444 112.017942,46.6204444 C113.988495,46.6204444 115.712908,45.7642667 116.57583,45.1825778 L118.5149,47.7226667 C118.022619,48.0896 116.020583,50.1688889 111.309573,50.1688889 C106.630046,50.1688889 103.212703,47.2931556 103.212703,42.3054222 C103.212703,37.3176889 106.907669,34.4718222 111.402591,34.4718222 C115.897513,34.4718222 119.00718,37.44 119.00718,41.8474667 C119.00718,42.5813333 118.945645,43.4673778 118.945645,43.4673778 L118.945645,43.4673778 Z M114.41924,40.6840889 C114.389188,39.3073778 113.373144,37.6561778 111.309573,37.6561778 C109.277485,37.6561778 108.231388,39.2462222 108.169853,40.6840889 L114.41924,40.6840889 L114.41924,40.6840889 Z" id="Fill-5" fill="#FFFFFF"></path>
  <path d="M132.185702,32.6357333 L126.706219,32.6357333 L126.706219,49.8332444 L121.717586,49.8332444 L121.717586,32.6357333 L116.236671,32.6357333 L116.236671,28.7189333 L132.185702,28.7189333 L132.185702,32.6357333" id="Fill-6" fill="#FFFFFF"></path>
  <path d="M140.284003,39.2462222 L140.067915,39.2462222 C139.791723,39.0926222 139.144889,38.8792889 138.283398,38.8792889 C137.174336,38.8792889 136.37438,39.4908444 136.003738,39.9800889 C135.634528,40.4693333 135.233835,41.4492444 135.233835,43.1317333 L135.233835,49.8332444 L130.308167,49.8332444 L130.308167,34.7491556 L135.233835,34.7491556 L135.203783,36.8896 L135.265318,36.8896 C136.126809,35.2369778 137.390424,34.4718222 139.021819,34.4718222 C140.037863,34.4718222 140.560195,34.7491556 140.560195,34.7491556 L140.284003,39.2462222" id="Fill-7" fill="#FFFFFF"></path>
  <path d="M144.59432,33.0040889 C142.931442,33.0040889 141.792328,31.9943111 141.792328,30.464 C141.792328,28.9649778 142.931442,27.9253333 144.59432,27.9253333 C146.257198,27.9253333 147.396312,28.9649778 147.396312,30.464 C147.396312,31.9943111 146.257198,33.0040889 144.59432,33.0040889 L144.59432,33.0040889 Z M142.130055,34.7491556 L147.055723,34.7491556 L147.055723,49.8332444 L142.130055,49.8332444 L142.130055,34.7491556 Z" id="Fill-8" fill="#FFFFFF"></path>
  <path d="M163.837623,49.8332444 L159.126613,49.8332444 L159.033595,48.2417778 C158.388192,48.8846222 157.15606,50.1688889 154.693226,50.1688889 C152.014304,50.1688889 149.18226,48.7324444 149.18226,45.3660444 C149.18226,41.9996444 152.291928,40.8675556 155.09392,40.7452444 L158.911956,40.5930667 L158.911956,40.256 C158.911956,38.6659556 157.772842,37.8396444 155.802288,37.8396444 C153.861787,37.8396444 151.922717,38.6958222 151.152813,39.1850667 L149.859146,36.0035556 C151.152813,35.3592889 153.522629,34.4718222 156.356104,34.4718222 C159.188148,34.4718222 160.820974,35.1146667 162.020192,36.2168889 C163.19079,37.3176889 163.837623,38.7868444 163.837623,41.3269333 L163.837623,49.8332444 L163.837623,49.8332444 Z M158.942008,43.1928889 L156.509226,43.3450667 C155.000901,43.4076444 154.107928,44.0504889 154.107928,45.1825778 C154.107928,46.3445333 155.062437,47.0485333 156.417639,47.0485333 C157.741359,47.0485333 158.634333,46.1909333 158.942008,45.6718222 L158.942008,43.1928889 L158.942008,43.1928889 Z" id="Fill-9" fill="#FFFFFF"></path>
  <path d="M182.741768,46.7740444 C182.741768,50.0167111 181.910329,51.9139556 180.433488,53.2920889 C178.955215,54.6673778 176.923127,55.6771556 173.444249,55.6771556 C169.933888,55.6771556 167.131896,54.208 166.0858,53.4442667 L168.117888,50.1688889 C169.010862,50.8430222 171.320574,51.8840889 173.351231,51.8840889 C175.383319,51.8840889 176.399363,51.2398222 176.923127,50.6908444 C177.44689,50.1077333 177.846153,49.0368 177.846153,47.6913778 L177.846153,47.2007111 L177.786049,47.2007111 C176.861592,48.3953778 175.383319,49.3425778 173.013504,49.3425778 C169.288485,49.3425778 165.838229,46.7740444 165.838229,41.9086222 C165.838229,37.0432 169.288485,34.4718222 173.013504,34.4718222 C175.567924,34.4718222 177.014714,35.6352 177.816101,36.6762667 L177.877636,36.6762667 L177.816101,34.7491556 L182.741768,34.7491556 L182.741768,46.7740444 L182.741768,46.7740444 Z M174.42881,38.2976 C172.2436,38.2976 170.858345,39.8890667 170.858345,41.9384889 C170.858345,44.0192 172.2436,45.6106667 174.42881,45.6106667 C176.615452,45.6106667 177.969223,44.0192 177.969223,41.9384889 C177.969223,39.8890667 176.615452,38.2976 174.42881,38.2976 L174.42881,38.2976 Z" id="Fill-10" fill="#FFFFFF"></path>
  <path d="M199.829913,43.4673778 L189.024069,43.4673778 C189.238727,45.6419556 190.901604,46.6204444 192.903641,46.6204444 C194.872763,46.6204444 196.598607,45.7642667 197.460098,45.1825778 L199.400599,47.7226667 C198.906887,48.0896 196.904851,50.1688889 192.195272,50.1688889 C187.514314,50.1688889 184.096971,47.2931556 184.096971,42.3054222 C184.096971,37.3176889 187.791937,34.4718222 192.286859,34.4718222 C196.781781,34.4718222 199.892879,37.44 199.892879,41.8474667 C199.892879,42.5813333 199.829913,43.4673778 199.829913,43.4673778 L199.829913,43.4673778 Z M195.304939,40.6840889 C195.273456,39.3073778 194.257412,37.6561778 192.195272,37.6561778 C190.163184,37.6561778 189.115656,39.2462222 189.055552,40.6840889 L195.304939,40.6840889 L195.304939,40.6840889 Z" id="Fill-11" fill="#FFFFFF"></path>
  <path d="M28.9141182,26.8956444 C25.4824649,26.8956444 22.6890591,24.1208889 22.6890591,20.7104 L22.6890591,9.15768889 L20.7642994,9.15768889 C18.5161229,9.15768889 16.6858125,10.9767111 16.6858125,13.2110222 L16.6858125,29.2323556 C16.6858125,31.4680889 18.5161229,33.2856889 20.7642994,33.2856889 L31.7533176,33.2856889 C34.0014941,33.2856889 35.8303735,31.4680889 35.8303735,29.2323556 L35.8303735,26.8956444 L28.9141182,26.8956444" id="Fill-12" fill="#E9A02E"></path>
  <path d="M12.6144807,43.9409778 C9.18282742,43.9409778 6.38942159,41.1648 6.38942159,37.7543111 L6.38942159,26.2030222 L4.46466194,26.2030222 C2.21505437,26.2030222 0.386174941,28.0206222 0.386174941,30.2563556 L0.386174941,46.2762667 C0.386174941,48.512 2.21505437,50.3310222 4.46466194,50.3310222 L15.452249,50.3310222 C17.7018566,50.3310222 19.530736,48.512 19.530736,46.2762667 L19.530736,43.9409778 L12.6144807,43.9409778" id="Fill-13" fill="#46B0BE"></path>
  <path d="M20.7642994,35.4190222 C17.3312151,35.4190222 14.5392403,32.6428444 14.5392403,29.2323556 L14.5392403,17.6810667 L12.6144807,17.6810667 C10.3648731,17.6810667 8.5359937,19.4986667 8.5359937,21.7344 L8.5359937,37.7543111 C8.5359937,39.9900444 10.3648731,41.8076444 12.6144807,41.8076444 L23.6020678,41.8076444 C25.8516753,41.8076444 27.6805548,39.9900444 27.6805548,37.7543111 L27.6805548,35.4190222 L20.7642994,35.4190222" id="Fill-14" fill="#5FB77A"></path>
</svg>

app/views/application/_nav.html.slim
.top-bar-red
.top-bar-yellow
.top-bar-green
.top-bar-blue

nav.application-navigation
  ul.application-navigation-list
    - if user_signed_in?
      li.application-navigation-list-item= image_tag current_user.avatar_url, class: 'user-profile-image'
      li.application-navigation-list-item= link_to current_user.github, current_user
      li.application-navigation-list-item= link_to "Submit Repo", new_repo_path
      li.application-navigation-list-item= link_to "Sign Out", destroy_user_session_path, method: :delete
    - else
      li.application-navigation-list-item= link_to 'Log in', user_github_omniauth_authorize_path

h1.application-logo
  = link_to root_path
    = render "logo"

app/views/application/_thoughtbot.html.slim
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="300px" height="300px" viewBox="0 0 300 300" class="credits-logo">
  <path d="M204.8,211.4l-3.2-3.2c1.7-1.3,2.9-3.4,2.9-5.8c0-4-3.2-7.2-7.2-7.2s-7.2,3.2-7.2,7.2 c0,2.4,1.1,4.5,2.9,5.8l-3.2,3.2c-2.6-2.2-4.2-5.3-4.2-8.9c0-2.9,1.1-4.5,2.8-7.5H188v-37h-5v77.4l3,2v6.7h-35v-6.7l4.2-1.3h0.8 v-24h-12v23.4l5,2v6.3l-35,0.1v-6.3l3.2-2.2l-0.2-77.1h-5v37h-0.3c1.7,3,2.8,4.6,2.8,7.5c0,3.6-1.6,6.8-4.2,8.9l-3.2-3.2 c1.8-1.3,2.9-3.4,2.9-5.8c0-4-3.2-7.2-7.2-7.2s-7.2,3.2-7.2,7.2c0,2.3,1.1,4.4,2.9,5.8l-3.2,3.2c-2.5-2.1-4.1-5.4-4.1-8.9 c0-2.9,0.9-5.5,2.9-7.6v-56.8c0-2.2,1.8-3.9,4-3.9h104c2.2,0,4,1.8,4,3.9v56.8c2,2,2.9,4.7,2.9,7.6 C208.9,206,207.3,209.3,204.8,211.4z M123.5,88h52.9c2.2,0,4.5,1.2,4.5,3.4v34.5c0,2.2-2.4,4.1-4.5,4.1h-52.9 c-2.2,0-4.5-1.9-4.5-4.1V91.4C119,89.2,121.4,88,123.5,88z M171,77l-3.2,4.5c-4-3.9-10.6-6.5-17.8-6.5c-7.3,0-13.8,2.6-17.9,6.5 l-3.2-4.6c5-4.5,12.6-7.4,21-7.4C158.4,69.6,166,72.5,171,77z M171,69.9c-5.5-4.1-12.9-6.4-20.8-6.4c-7.9,0-15.3,2.3-20.8,6.4 c-1.3,1-2.4,2-3.4,3.2l-3.2-4.6C129,62.1,139,58,150.2,58c11,0,20.7,3.9,26.9,10l-3.2,4.6C173.1,71.7,172.1,70.8,171,69.9z M150,46.9c13.6,0,25.7,4.9,33.4,12.5l-3.2,4.5c-6.6-6.9-17.7-11.5-30.2-11.5c-12.6,0-23.7,4.6-30.3,11.6l-3.2-4.5 C124.3,51.8,136.4,46.9,150,46.9z M150,21.7C79.1,21.7,21.7,79.1,21.7,150S79.2,278.3,150,278.3c70.9,0,128.3-57.5,128.3-128.3 C278.3,79.1,220.9,21.7,150,21.7z M136.5,109.5c-1.9,0-3.4-1.5-3.4-3.4s1.5-3.5,3.4-3.5s3.5,1.5,3.5,3.5 C140,107.9,138.4,109.5,136.5,109.5z M136.5,99.3c-3.7,0-6.7,3-6.7,6.7s3,6.7,6.7,6.7s6.7-3,6.7-6.7 C143.3,102.3,140.2,99.3,136.5,99.3z M163.6,109.5c-1.9,0-3.4-1.5-3.4-3.4s1.5-3.5,3.4-3.5c1.9,0,3.5,1.5,3.5,3.5 C167,107.9,165.5,109.5,163.6,109.5z M163.6,99.3c-3.7,0-6.8,3-6.8,6.7s3,6.7,6.8,6.7c3.7,0,6.7-3,6.7-6.7S167.3,99.3,163.6,99.3z "/>
</svg>